### ISSUE TITLE
Linux Problems

### ISSUE THREAD

**Issue by whipowill** [timbergeron/QSS-M#17]
Tim, I tried to update to your latest version, which I haven't updated in a while.  I was met w/ this error:

```
./QSS-M-l64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./QSS-M-l64)
./QSS-M-l64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./QSS-M-l64)
```

It appears my version of Linux, which is the latest Zorin OS, only goes up to GLIB 2.31.

```
$ ldd --version
ldd (Ubuntu GLIBC 2.31-0ubuntu9.9) 2.31
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by timbergeron** [comment]
This is likely related to downstream Quakespasm requirements? Is this the same for latest QS?

**Comment by fzwoch** [comment]
Common issue when binaries are compiled with a newer glibc.

You can mark symbols to be linked to an older version explicitly.

See https://github.com/wheybags/glibc_version_header for more info/helpful scripts.

**Comment by timbergeron** [comment]
@whipowill this is the latest built on 2.27, let me know if it works

[QSS-M-l64.zip](https://github.com/user-attachments/files/17123508/QSS-M-l64.zip)

**Comment by whipowill** [comment]
Same issue but strangely the errors are reversed in sequence:

```
./QSS-M-l64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./QSS-M-l64)
./QSS-M-l64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./QSS-M-l64)
```

**Comment by timbergeron** [comment]
Round 2. Try this version 🤞
[QSS-M-l64.zip](https://github.com/user-attachments/files/17140895/QSS-M-l64.zip)

**Comment by whipowill** [comment]
I got this error:

```
./QSS-M-l64: symbol lookup error: ./QSS-M-l64: undefined symbol: SDL_FlashWindow
```

For what it's worth, I have another prebuilt game that is now also giving me the same error.  This is bc apparently a Linux OS version that is 3 years old is "leaving you behind" age.

I'm going to try and solve this myself by building the new version of this library by following these directions:
https://www.jertype.com/upgrading-glibc/

If it doesn't work I may just upgrade my OS this weekend.

**Comment by timbergeron** [comment]
The error means your version of SDL2 is outdated, SDL_FlashWindowi is a newer function.

**Comment by whipowill** [comment]
I'm preparing to update my OS tomorrow.  I'm sorry for taking up your time.

**Comment by whipowill** [comment]
I updated my OS and the latest version of QSS-M is working now, but I did have to do these manually on my new OS:

```
$ sudo apt-get install libopusfile0
$ sudo apt-get install libmad0
```

And my bots crash the game, so I will have to investigate why.  Thank you for trying to help me.
