### ISSUE TITLE
Sound Question

### ISSUE THREAD

**Issue by whipowill** [timbergeron/QSS-M#18]
Wanted to inquire about sounds being muted based on distance.  It seems like all sounds play at the same volume regardless of where on the board they occur.

**Comment by timbergeron** [comment]
Howdy! Can you give me an example where this happens or post video clip. I play lots of games online and have never noticed.

**Comment by whipowill** [comment]
I think this was a mistake on my part, and what was happening is most of the maps I play are small maps, and so the sound does carry to all corners of the maps.  So every footstep, every weapon pickup, gets played for me, even when enemies are on the other side of the board.  

But on larger levels, sound does trickle off and become unaudible with distance.  Probably not worth the trouble of making that distance a configurable setting, as I'm probably the first guy in 30 years to raise the issue.  This all stems from me having added footsteps in my mod, so it's lots of pitter-patter sounds even when nobody is close enough to justify it.

**Comment by timbergeron** [comment]
this was a proquake feature for sound back to DOSquake levels, which increased the distance https://github.com/timbergeron/QSS-M/commit/c971c14fd2df297c7c38e795e8f1c514efe1ce58

**Comment by whipowill** [comment]
It's at your discretion, but if I had the option to control that, would be clutch.  The idea behind footsteps is to create situational awareness, but kinda lame if you hear steps 100 ft away and you turn around expecting to see somebody who isn't there.  A followup question is do the sounds actually "trickle off" and become quieter, or is it just a distance cutoff and the volume never diminishes for something that occurs right at the edge of that distance?
