### ISSUE TITLE
Wrong map rotation when entering a splitgate in the different singleplayer campaigns. 

### ISSUE THREAD

**Issue by lonepeakmusic** [timbergeron/QSS-M#19]
Hya ! 

I'm trying to play the classic quake campaign and the new extensions via QSS-M, everything work great except that when I'm on the hub and enter in a portal/splitgate to start a level it sends me on DM maps. It's the same if i load a level manually (eg :  e1m1) and then finish the level. It sends me on a DM map. 
My deathmatch parameter is set to "0". 

Is there any fix for this ? 

Thanks a lot !

**Comment by timbergeron** [comment]
The temporary fix for this is setting `sv_map_rotation ""` I have fixed the default behavior for this in the next version. https://github.com/timbergeron/QSS-M/commit/55cabd793c7e4e477e26dcf1096b9de39b30b937 Let me know if that works for you :)

**Comment by lonepeakmusic** [comment]
> 

Awesome! I added this in my autoexec, it works like a charm, thanks a lot !
